require_relative '../../app/api/v1/books.rb'
require_relative '../../app/api/v1/borrowed_books.rb'
require_relative '../../app/api/v1/issued_books.rb'
require_relative '../../app/api/v1/returned_books.rb'
require_relative '../../app/api/v1/users.rb'
require_relative '../../app/api/v1/base.rb'
require_relative '../../app/api/api.rb'